"""
Pre-build script for PlatformIO.

Runs `npm run build` inside the `web/` directory, then converts
the resulting `web/dist/index.html` into `src/web_ui.h` so it can
be compiled directly into the firmware binary.

PlatformIO runs this automatically via `extra_scripts = pre:scripts/embed_web.py`.
"""

Import('env')  # noqa: F821 — injected by PlatformIO

import os
import subprocess
import sys

PROJECT_DIR = env['PROJECT_DIR']  # noqa: F821
WEB_DIR     = os.path.join(PROJECT_DIR, 'web')
DIST_FILE   = os.path.join(WEB_DIR, 'dist', 'index.html')
HEADER_FILE = os.path.join(PROJECT_DIR, 'src', 'web_ui.h')

# ---------------------------------------------------------------------------

print('\n[embed_web] Building React app...')

npm = 'npm.cmd' if sys.platform == 'win32' else 'npm'
result = subprocess.run([npm, 'run', 'build'], cwd=WEB_DIR)

if result.returncode != 0:
    print('[embed_web] ERROR: npm build failed.')
    sys.exit(1)

# ---------------------------------------------------------------------------

print('[embed_web] Embedding into web_ui.h...')

with open(DIST_FILE, 'r', encoding='utf-8') as f:
    html = f.read()

# Use a delimiter that will never appear in minified React output.
DELIM = 'AMBILIGHT_UI'

header = (
    '#pragma once\n'
    '// Auto-generated by scripts/embed_web.py — do not edit manually.\n'
    f'static const char WEB_UI[] = R"{DELIM}({html}){DELIM}";\n'
)

with open(HEADER_FILE, 'w', encoding='utf-8') as f:
    f.write(header)

size_kb = len(html) / 1024
print(f'[embed_web] web_ui.h written ({size_kb:.1f} KB).\n')
