#include "WebPortal.h"
#include "Config.h"
#include "NetworkManager.h"
#include "LEDController.h"
#include "RemoteLogger.h"
#include "web_ui.h"   // auto-generated by scripts/embed_web.py
#include <ArduinoJson.h>
#include <WiFi.h>

static void sendJson(WebServer& server, const JsonDocument& doc) {
    String out;
    serializeJson(doc, out);
    server.send(200, "application/json", out);
}

WebPortal& WebPortal::instance() {
    static WebPortal inst;
    return inst;
}

// Captive portal: redirect all unknown paths to root.
static void redirectToRoot(WebServer& server) {
    server.sendHeader("Location", "/");
    server.send(302, "text/plain", "");
}

void WebPortal::begin() {
    _server.on("/",                    HTTP_GET,  [this]() { handleRoot();               });
    _server.on("/status",              HTTP_GET,  [this]() { handleStatus();             });
    _server.on("/config",              HTTP_GET,  [this]() { handleConfig();             });
    _server.on("/metrics",             HTTP_GET,  [this]() { handleMetrics();            });
    _server.on("/save/network",        HTTP_POST, [this]() { handleSaveNetwork();        });
    _server.on("/save/leds",           HTTP_POST, [this]() { handleSaveLeds();           });
    _server.on("/save/calibration",    HTTP_POST, [this]() { handleSaveCalibration();    });
    _server.on("/preview/calibration", HTTP_POST, [this]() { handlePreviewCalibration(); });
    _server.on("/save/mode",           HTTP_POST, [this]() { handleSaveMode();           });

    // Captive portal detection URLs used by major OSes.
    // Returning a redirect causes the OS to open the browser automatically.
    auto cp = [this]() { redirectToRoot(_server); };
    _server.on("/generate_204",                HTTP_GET, cp); // Android
    _server.on("/gen_204",                     HTTP_GET, cp); // Android (alt)
    _server.on("/hotspot-detect.html",         HTTP_GET, cp); // iOS / macOS
    _server.on("/library/test/success.html",   HTTP_GET, cp); // iOS (alt)
    _server.on("/connecttest.txt",             HTTP_GET, cp); // Windows
    _server.on("/redirect",                    HTTP_GET, cp); // Windows (alt)
    _server.onNotFound([this]() { redirectToRoot(_server); });

    _server.begin();
    Log.println("[Web] HTTP server started on port 80");
}

void WebPortal::handle() {
    _server.handleClient();
}

void WebPortal::handleRoot() {
    // WEB_UI is ~70 KB — stream in 4 KB chunks to avoid heap exhaustion.
    const size_t kChunk = 4096;
    const char*  p      = WEB_UI;
    size_t       rem    = strlen(WEB_UI);

    _server.setContentLength(rem);
    _server.send(200, "text/html", "");

    while (rem > 0) {
        size_t n = rem < kChunk ? rem : kChunk;
        _server.sendContent(p, n);
        p   += n;
        rem -= n;
    }
}

void WebPortal::handleStatus() {
    auto& net = NetworkManager::instance();
    JsonDocument doc;
    doc["ip"]                 = net.ipAddress();
    doc["mode"]               = net.mode();
    doc["ssid"]               = WiFi.SSID();
    doc["rssi"]               = WiFi.RSSI();
    doc["connected"]          = net.isConnected();
    doc["gateway"]            = WiFi.gatewayIP().toString();
    doc["preferred_last_oct"] = PREFERRED_IP_LAST_OCTET;
    sendJson(_server, doc);
}

void WebPortal::handleConfig() {
    auto& cfg = Config::instance();

    char colorHex[8];
    snprintf(colorHex, sizeof(colorHex), "#%02x%02x%02x",
             cfg.colorR, cfg.colorG, cfg.colorB);

    JsonDocument doc;
    doc["wifi_ssid"]    = cfg.wifiSSID;
    doc["ota_host"]     = cfg.otaHostname;
    doc["num_leds"]     = cfg.numLeds;
    doc["max_leds"]     = MAX_LEDS;
    doc["brightness"]   = cfg.brightness;
    doc["color"]        = colorHex;
    doc["led_mode"]     = cfg.ledMode;
    doc["led_top"]      = cfg.ledTop;
    doc["led_right"]    = cfg.ledRight;
    doc["led_bottom"]   = cfg.ledBottom;
    doc["led_left"]     = cfg.ledLeft;
    doc["start_corner"] = cfg.startCorner;
    doc["clockwise"]    = cfg.clockwise;
    doc["gamma"]        = cfg.gamma;
    doc["saturation"]   = cfg.saturation;
    doc["wb_r"]         = cfg.whiteBalanceR;
    doc["wb_g"]         = cfg.whiteBalanceG;
    doc["wb_b"]         = cfg.whiteBalanceB;
    sendJson(_server, doc);
}

void WebPortal::handleMetrics() {
    JsonDocument doc;
    doc["heap_free"]  = ESP.getFreeHeap();
    doc["heap_total"] = ESP.getHeapSize();
    doc["heap_min"]   = ESP.getMinFreeHeap();
    doc["uptime_s"]   = millis() / 1000;
    doc["cpu_mhz"]    = ESP.getCpuFreqMHz();
    sendJson(_server, doc);
}

void WebPortal::handleSaveNetwork() {
    auto& cfg = Config::instance();

    if (_server.hasArg("wifi_ssid"))
        cfg.wifiSSID = _server.arg("wifi_ssid");

    if (_server.hasArg("wifi_pass") && !_server.arg("wifi_pass").isEmpty())
        cfg.wifiPassword = _server.arg("wifi_pass");

    if (_server.hasArg("ota_host") && !_server.arg("ota_host").isEmpty())
        cfg.otaHostname = _server.arg("ota_host");

    if (_server.hasArg("ota_pass") && !_server.arg("ota_pass").isEmpty())
        cfg.otaPassword = _server.arg("ota_pass");

    cfg.save();
    Log.println("[Web] Network config saved — restarting.");

    _server.send(200, "application/json",
                 "{\"message\":\"Network settings saved. Restarting in 1 s...\"}");
    delay(1000);
    ESP.restart();
}

void WebPortal::handleSaveLeds() {
    auto& cfg  = Config::instance();
    auto& leds = LEDController::instance();
    bool  plain = (cfg.ledMode == 0);

    Log.printf("[Web] saveLeds: mode=%s num_leds=%s brightness=%s\n",
               plain ? "plain" : "dynamic",
               _server.hasArg("num_leds") ? _server.arg("num_leds").c_str() : "(none)",
               _server.hasArg("brightness") ? _server.arg("brightness").c_str() : "(none)");

    if (_server.hasArg("num_leds")) {
        uint16_t n = static_cast<uint16_t>(_server.arg("num_leds").toInt());
        if (n > 0) {
            cfg.numLeds = n;
            if (plain) leds.setNumLeds(n);
        }
    }

    if (_server.hasArg("brightness")) {
        cfg.brightness = static_cast<uint8_t>(_server.arg("brightness").toInt());
        leds.setBrightness(cfg.brightness);
    }

    if (_server.hasArg("color")) {
        String hex = _server.arg("color");
        if (hex.startsWith("#")) hex = hex.substring(1);
        long val   = strtol(hex.c_str(), nullptr, 16);
        cfg.colorR = (val >> 16) & 0xFF;
        cfg.colorG = (val >>  8) & 0xFF;
        cfg.colorB =  val        & 0xFF;
        if (plain) leds.setColor(cfg.colorR, cfg.colorG, cfg.colorB);
    }

    if (_server.hasArg("gamma"))
        cfg.gamma = _server.arg("gamma").toFloat();

    if (_server.hasArg("saturation"))
        cfg.saturation = _server.arg("saturation").toFloat();

    if (_server.hasArg("wb_r"))
        cfg.whiteBalanceR = static_cast<uint8_t>(_server.arg("wb_r").toInt());

    if (_server.hasArg("wb_g"))
        cfg.whiteBalanceG = static_cast<uint8_t>(_server.arg("wb_g").toInt());

    if (_server.hasArg("wb_b"))
        cfg.whiteBalanceB = static_cast<uint8_t>(_server.arg("wb_b").toInt());

    cfg.save();
    Log.println("[Web] LED config applied.");

    _server.send(200, "application/json", "{\"message\":\"Applied.\"}");
}

// ---------------------------------------------------------------------------
// Calibration helpers
// ---------------------------------------------------------------------------

static uint8_t parseCalibrationParam(WebServer& server, const char* key, uint8_t defaultVal) {
    if (!server.hasArg(key)) return defaultVal;
    int v = server.arg(key).toInt();
    return (v >= 0 && v <= 255) ? (uint8_t)v : defaultVal;
}

void WebPortal::handleSaveCalibration() {
    auto& cfg  = Config::instance();
    auto& leds = LEDController::instance();

    cfg.ledTop     = parseCalibrationParam(_server, "led_top",     cfg.ledTop);
    cfg.ledRight   = parseCalibrationParam(_server, "led_right",   cfg.ledRight);
    cfg.ledBottom  = parseCalibrationParam(_server, "led_bottom",  cfg.ledBottom);
    cfg.ledLeft    = parseCalibrationParam(_server, "led_left",    cfg.ledLeft);

    if (_server.hasArg("start_corner")) {
        int v = _server.arg("start_corner").toInt();
        if (v >= 0 && v <= 3) cfg.startCorner = (uint8_t)v;
    }
    if (_server.hasArg("clockwise"))
        cfg.clockwise = (_server.arg("clockwise") != "0");

    // Keep numLeds in sync so FastLED drives the right count.
    uint16_t total = cfg.ledTop + cfg.ledRight + cfg.ledBottom + cfg.ledLeft;
    if (total > 0) {
        cfg.numLeds = total;
        leds.setNumLeds(total);
    }

    cfg.save();
    Log.println("[Web] Calibration saved.");

    // Show the preview so the user immediately sees the result on the strip.
    leds.showCalibrationPreview(cfg.startCorner, cfg.clockwise,
                                cfg.ledTop, cfg.ledRight,
                                cfg.ledBottom, cfg.ledLeft);

    _server.send(200, "application/json", "{\"message\":\"Calibration saved.\"}");
}

void WebPortal::handlePreviewCalibration() {
    uint8_t top    = parseCalibrationParam(_server, "led_top",     Config::instance().ledTop);
    uint8_t right  = parseCalibrationParam(_server, "led_right",   Config::instance().ledRight);
    uint8_t bottom = parseCalibrationParam(_server, "led_bottom",  Config::instance().ledBottom);
    uint8_t left   = parseCalibrationParam(_server, "led_left",    Config::instance().ledLeft);

    uint8_t corner = Config::instance().startCorner;
    if (_server.hasArg("start_corner")) {
        int v = _server.arg("start_corner").toInt();
        if (v >= 0 && v <= 3) corner = (uint8_t)v;
    }

    bool cw = Config::instance().clockwise;
    if (_server.hasArg("clockwise"))
        cw = (_server.arg("clockwise") != "0");

    LEDController::instance().showCalibrationPreview(corner, cw, top, right, bottom, left);
    _server.send(200, "application/json", "{\"message\":\"Preview applied.\"}");
}

void WebPortal::handleSaveMode() {
    auto& cfg  = Config::instance();
    auto& leds = LEDController::instance();

    if (_server.hasArg("led_mode")) {
        int m = _server.arg("led_mode").toInt();
        if (m == 0 || m == 1) cfg.ledMode = (uint8_t)m;
    }
    cfg.save();
    Log.printf("[Web] Mode set to %s\n", cfg.ledMode == 1 ? "dynamic" : "plain");

    if (cfg.ledMode == 0) {
        // When switching back to plain, restore the static color immediately.
        leds.setNumLeds(cfg.numLeds);
        leds.setColor(cfg.colorR, cfg.colorG, cfg.colorB);
    } else {
        // When switching to dynamic, clear the strip so it stays dark
        // until the first UDP frame arrives.
        leds.setColor(0, 0, 0);
    }

    _server.send(200, "application/json", "{\"message\":\"Mode saved.\"}");
}
